# Generated by Django 4.1.2 on 2022-11-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0003_alter_spotifytoken_expires_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spotifytoken",
            name="expires_in",
            field=models.DateTimeField(null=True),
        ),
    ]
